### ISSUE TITLE
Tracking Issue for Feature Compatibility

### ISSUE THREAD

**Issue by JasonGrace2282** [JasonGrace2282/director5#9]
# Progress
This issue tracks what's needed for feature compatibility with Director4

## Essential
- [x] Orchestrator setup for hosting sites (#5)
- [x] Manager setup for creating sites (#8)
- [ ] Site dashboard
- [ ] Manager actions for managing sites
  - [ ] Adding Database
  - [ ] Removing Database
  - [x] Deleting Site
- [ ] Terminal into container
- [ ] Web Editor
- [ ] Site requests
- [ ] Custom domains

## Later
- [ ] Show disabled message for dynamic sites
- [ ] ~~Make Web Editor collaborative~~ (adds too much technical complexity)
- [ ] Git integration
- [ ] Docs about how it works
  - [ ] Chatbot trained off of docs?
- [x] Testing Framework
